name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
- master
- dev

variables:
  TestUsername: testuser
  TestSubscription: testsubscription
  TestWebSpace: testwebspace

jobs:
- job: "CleanupStampAndSetupKuduLite"
  pool:
        vmImage: 'ubuntu-16.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python -m pip install requests
      displayName: Install Python Prerequisites
    - task: PythonScript@0
      displayName: Remove Previous Mesh Images
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/remove_mesh_images.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword)
    - task: PythonScript@0
      displayName: Add KuduLite Image
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/update_mesh_image.py
        arguments: --image-name mcr.microsoft.com/azure-functions/kudulite:kudu-2.9 --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --placeholder-id "v=1,k=f,e=~2,a=0" --hostname-type Repository

- job: "BuildAndUpdateV2Python36Image"
  dependsOn: "CleanupStampAndSetupKuduLite"
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: $(knownHostsEntry)
        sshPublicKey: $(sshPublicKey)
        sshPassphrase: $(sshPassphrase)
        sshKeySecureFile: id_rsa
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python -m pip install requests
      displayName: Install Python Prerequisites
    - bash: |
        git clone --single-branch --branch master git@github.com:maiqbal11/azure-functions-docker.git
        git clone --single-branch --branch master git@github.com:maiqbal11/azure-functions-docker-private.git
      displayName: Clone Required Repos
    - bash: |
        docker build -t local/azure-functions-base:python36-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/base.Dockerfile --build-arg HOST_VERSION="test-2.0.0" azure-functions-docker/host
        docker build -t local/azure-functions-python-deps:python36-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/python/python36-deps.Dockerfile azure-functions-docker/host
        docker build -t local/azure-functions-python:python36-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/python/python36.Dockerfile --build-arg BASE_IMAGE="local/azure-functions-base:python36-test-2.0" --build-arg BASE_PYTHON_IMAGE="local/azure-functions-python-deps:python36-test-2.0" azure-functions-docker/host
        docker build -t local/azure-functions-mesh:python36-test-2.0 -f azure-functions-docker-private/host/2.0/stretch/amd64/mesh.Dockerfile --build-arg BASE_IMAGE="local/azure-functions-python:python36-test-2.0" --build-arg HOST_VERSION="test-2.0.0" azure-functions-docker-private/host
        docker tag local/azure-functions-mesh:python36-test-2.0 maheeri/python36-test-2.0:$TAGNUMBER
      env:
        TAGNUMBER: $(Build.BuildNumber)
      displayName: Build Docker Image
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: myDockerHub
    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        command: push
        repository: maheeri/python36-test-2.0
        tags: |
          $(Build.BuildNumber)
    - task: PythonScript@0
      displayName: Update Mesh Image
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/update_mesh_image.py
        arguments: --image-name maheeri/python36-test-2.0:$(Build.BuildNumber) --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --placeholder-id "v=1,k=f,e=~2,a=0" --hostname-type Standard

- job: "BuildAndUpdateV2Python37Image"
  dependsOn: "CleanupStampAndSetupKuduLite"
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: $(knownHostsEntry)
        sshPublicKey: $(sshPublicKey)
        sshPassphrase: $(sshPassphrase)
        sshKeySecureFile: id_rsa
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python -m pip install requests
      displayName: Install Python Prerequisites
    - bash: |
        git clone --single-branch --branch master git@github.com:maiqbal11/azure-functions-docker.git
        git clone --single-branch --branch master git@github.com:maiqbal11/azure-functions-docker-private.git
      displayName: Clone Required Repos
    - bash: |
        docker build -t local/azure-functions-base:python37-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/base.Dockerfile --build-arg HOST_VERSION="test-2.0.0" azure-functions-docker/host
        docker build -t local/azure-functions-python-deps:python37-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/python/python37-deps.Dockerfile azure-functions-docker/host
        docker build -t local/azure-functions-python:python37-test-2.0 -f azure-functions-docker/host/2.0/stretch/amd64/python/python37.Dockerfile --build-arg BASE_IMAGE="local/azure-functions-base:python37-test-2.0" --build-arg BASE_PYTHON_IMAGE="local/azure-functions-python-deps:python37-test-2.0" azure-functions-docker/host
        docker build -t local/azure-functions-mesh:python37-test-2.0 -f azure-functions-docker-private/host/2.0/stretch/amd64/mesh-py37.Dockerfile --build-arg BASE_IMAGE="local/azure-functions-python:python37-test-2.0" --build-arg HOST_VERSION="test-2.0.0" azure-functions-docker-private/host
        docker tag local/azure-functions-mesh:python37-test-2.0 maheeri/python37-test-2.0:$TAGNUMBER
      env:
        TAGNUMBER: $(Build.BuildNumber)
      displayName: Build Docker Image
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: myDockerHub
    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        command: push
        repository: maheeri/python37-test-2.0
        tags: |
          $(Build.BuildNumber)
    - task: PythonScript@0
      displayName: Update Mesh Image
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/update_mesh_image.py
        arguments: --image-name maheeri/python37-test-2.0:$(Build.BuildNumber) --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --placeholder-id "v=1,k=f,e=~2,a=0,r=python,rv=3.7" --hostname-type Standard

- job: "SetupStampAndDeployTestApps"
  dependsOn: ['BuildAndUpdateV2Python36Image',
              'BuildAndUpdateV2Python37Image']
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python -m pip install requests
      displayName: Install Python Prerequisites
    - task: PythonScript@0
      displayName: Wait For Image Updates
      inputs:
        scriptSource: inline
        script: |
          import time
          mins = 20
          time.sleep(60 * mins)
    - task: PythonScript@0
      displayName: Add Or Update Hosting Configuration
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/add_or_update_hosting_config.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword)
    - task: PythonScript@0
      displayName: Create User
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/create_user.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --publishing-username $(TestUsername) --publishing-password $(PublishingPassword) --name $(TestUsername)
    - task: PythonScript@0
      displayName: Create Subscription
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/create_subscription.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --user $(TestUsername) --name $(TestSubscription)
    - task: PythonScript@0
      displayName: Create WebSpace
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/create_webspace.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --subscription $(TestSubscription) --name $(TestWebSpace)
    - bash: |
        git clone --single-branch --branch master https://github.com/maiqbal11/azure-functions-devops-cli-test.git
      displayName: Clone Required Repos
    - task: PythonScript@0
      displayName: Create Function Sites
      inputs:
        scriptSource: filePath
        scriptPath: proxy_operations/create_function_sites.py
        arguments: --proxy-address $(ProxyAntaresCmdAddress) --proxy-username $(ProxyUsername) --proxy-password $(ProxyPassword) --subscription $(TestSubscription) --webspace $(TestWebSpace) --storage-account $(AzureWebJobsStorage)
    - task: PythonScript@0
      displayName: Zip Function Apps For Deployment
      inputs:
        scriptSource: filePath
        scriptPath: zip_function_apps.py
    - task: PythonScript@0
      displayName: Zip Deploy Function Apps
      inputs:
        scriptSource: filePath
        scriptPath: zip_deploy_apps.py
        arguments: --site-username $(TestUsername) --site-password $(PublishingPassword) --zipdeploy-address $(ZipDeployAddress)

- job: "RunTests"
  dependsOn: ['SetupStampAndDeployTestApps']
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - bash: |
        git clone --single-branch --branch master https://github.com/maiqbal11/azure-functions-devops-cli-test.git
      displayName: Clone Required Repos (azure-functions-devops-cli-test)
    - bash: |
        chmod +x run_tests/run_all_tests.sh
        run_tests/run_all_tests.sh
      workingDirectory: azure-functions-devops-cli-test
      env:
        STAMPADDRESS: $(StampAddress)
      displayName: Run Tests
